# hxgo lint configuration.

version: "2"

linters:
  default: all

  disable:
    - canonicalheader
    - containedctx
    - contextcheck
    - cyclop
    - depguard
    - dupword
    - errname
    - godox
    - ireturn
    - intrange
    - err113
    - errcheck
    - exhaustruct
    - exhaustive
    - forbidigo
    - funcorder
    - funlen
    - gocognit
    - gochecknoglobals
    - godot
    - inamedparam
    - unparam
    - tagalign
    - varnamelen
    - paralleltest
    - mnd
    - nestif
    - nolintlint
    - tagliatelle
    - testifylint
    - testpackage
    - wrapcheck
    - zerologlint

  settings:
    govet:
      enable:
        - fieldalignment

    errcheck:
      exclude-functions:
        - fmt.Fprint
        - fmt.Fprintf
        - fmt.Fprintln
        - fmt.Println
        - os.Close
        - strings.Builder.WriteString
        - (io.Closer).Close

    ireturn:
      allow:
        - error

    lll:
      line-length: 150

    tagliatelle:
      case:
        rules:
          yaml: snake

    revive:
      enable-all-rules: true
      rules:
        - name: atomic
        - name: line-length-limit
          severity: error
          arguments: [150]
        - name: unhandled-error
          exclude:
            - "**/*_test.go"
          arguments:
            - fmt.Printf
            - fmt.Println
            - strings.Builder.WriteString
            - strings.Builder.WriteByte
            - io.Closer.Close
            - net/http.ResponseWriter.Write
        - name: function-length
          arguments: [0, 0]
          disabled: false
          exclude: ["_test.go"]
        - name: cognitive-complexity
          arguments: [50]
        - name: cyclomatic
          arguments: [10]
        - name: max-control-nesting
          arguments: [7]
        - name: package-comments
          disabled: true
        - name: add-constant
          disabled: true
        - name: exported
          disabled: true
          arguments:
            - disableChecksOnTypes
            - disableChecksOnConstants
        - name: max-public-structs
          disabled: true
        - name: deep-exit
          disabled: true
        - name: confusing-naming
          disabled: true
        - name: flag-parameter
          disabled: true
        - name: confusing-results
          disabled: true
        - name: unused-parameter
          disabled: true

  exclusions:
    generated: lax
    rules:
      - path: (.+)_test.go
        linters:
          - gosec
          - dupl
          - goconst
      - path: helpers/(.+).go
        linters:
          - gosec
          - mnd
      - path: "(.+).go"
        linters:
          - staticcheck
        text: "could remove embedded field"

formatters:
  enable:
    - gofmt
    - goimports
